### ISSUE TITLE
查了一些很久以前的帖子，尝试对luaL_loadbuffer进行hook

### ISSUE THREAD

**Issue by Rh95-OSS** [jx3pak/PakV4-Extract#10]
但是没有在engine_lua5X64.dll里找到luaL_loadbuffer函数
麻烦请问下能给点什么思路吗

**Comment by Frozenuuuu** [comment]
同问

**Comment by jx3pak** [comment]
没研究lua加载，只研究了g_OpenFile。
你loadbuffer是为了加载其他lua？没必要啊，你都hook了，直接把插件隔离去掉不就好了？
