### ISSUE TITLE
编译后的程序无法解包

### ISSUE THREAD

**Issue by iderfl** [jx3pak/PakV4-Extract#3]
以下是输出的信息
File Path: F:\JX3\Pakv4\11970\000.dat
F:\JX3\Pakv4\11970\000.dat, hash=3623437587, skip exist

**Comment by a289672082** [comment]
这个代码已经废了 而且文件目录设计的极混乱

**Comment by jx3pak** [comment]
> 以下是输出的信息 File Path: F:\JX3\Pakv4\11970\000.dat F:\JX3\Pakv4\11970\000.dat, hash=3623437587, skip exist

传dat做什么？你要给出正确的内部资源路径。data\script\settings\ui\... 开头的那些。

**Comment by jx3pak** [comment]
> 这个代码已经废了 而且文件目录设计的极混乱

除了无界，所有其他版本通用。

**Comment by chaossnake** [comment]
作者大佬可以放个编译好的吗？小白老是编译出错：（

**Comment by chaossnake** [comment]
感谢！

**Comment by zhuifengshaonian1** [comment]
> > 这个代码已经废了 而且文件目录设计的极混乱
> 
> 除了无界，所有其他版本通用。



> > 以下是输出的信息 File Path: F:\JX3\Pakv4\11970\000.dat F:\JX3\Pakv4\11970\000.dat, hash=3623437587, skip exist
> 
> 传dat做什么？你要给出正确的内部资源路径。data\script\settings\ui... 开头的那些。

大大,怎么获取到内部资源路径?
