### ISSUE TITLE
如何获取最新版本的内部资源列表呢

### ISSUE THREAD

**Issue by pjwwx** [jx3pak/PakV4-Extract#7]
尝试着使用了一下，完全可以使用并正确解包。
但是一切的前提是拥有内部资源列表，请问如何获取全量的内部资源列表呢？

**Comment by pjwwx** [comment]
研究了一下，有一点思路
应该是hook掉g_FileHash这个函数，自己反编译实现相同功能并记录调用时候的输入列表然后保存
怎么注入...暂时还没思路
不知道行不行，不知道作者是怎么做的。

**Comment by jx3pak** [comment]
你说得对，就是hook
