### ISSUE TITLE
读取列表文件时，首个字符是中文时，会导致文件解析提前中断

### ISSUE THREAD

**Issue by ReduckProject** [jx3pak/PakV4-Extract#9]
data\source\player\f2\动作\f2b02dj圈圈b.ani
data\source\player\m2\动作\m2b02dj打坐c.ani
data\source\item\prop\d012420m2_hd_lod1.JsonInspack
data\source\item\prop\d007308_hd.jsoninspack
data\source\item\weapon\sword\rh_sword_179_hd.jsoninspack
data\source\item\prop\d005619_hd.jsoninspack
data\source\item\prop\d003772_hd.jsoninspack
data\source\item\prop\d007308_hd_lod1.mesh
裂蓝色_左.pss
data\source\item\weapon\sword\rh_sword_179_hd_lod1.mesh
data\source\other\hd特效\其他\pss\j_脚印冰地裂蓝色_右.pss
data\source\item\prop\d003772_hd_lod1.mesh
data\source\other\特效\贴图\qt_其他\b_冰山03.dds
data\source\item\weapon\sword\rh_sword_179_hd_lod1.JsonInspack
data\source\other\特效\贴图\qt_其他\b_冰山03.hdd2
----------------------------------------------------------------
比如文件列表如上，当读取 裂蓝色_左.pss 就中断了，后边的都解析不了

**Comment by Frozenuuuu** [comment]
请问如何获取文件啊

**Comment by jx3pak** [comment]
我这里正常
